apiVersion: v2
type: application
version: 25.0.0-bb.0
name: prometheus-operator-crds
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: |
  A Helm chart that collects custom resource definitions (CRDs) from the Prometheus Operator, allowing for seamless
  integration with GitOps tools
keywords:
  - prometheus
  - crds
# renovate: github=prometheus-operator/prometheus-operator
appVersion: v0.87.0
kubeVersion: ">=1.16.0-0"
sources:
  - https://github.com/prometheus-community/helm-charts
annotations:
  bigbang.dev/maintenanceTrack: bb_integrated
  bigbang.dev/applicationVersions: |
    - Prometheus: 21.0.0
dependencies:
  - name: prometheus-operator-crds
    version: 25.0.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: upstream